# Generated by Django 4.2.5 on 2023-09-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('dpi', models.CharField(max_length=13)),
                ('pasaporte', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('validar_horario', models.BooleanField(default=True)),
                ('Activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.departamento')),
                ('jefe_inmediato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.empleado')),
            ],
        ),
    ]
