# Generated by Django 4.2.5 on 2023-10-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('id', 'nombre')},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('nombre1', 'apellido1')},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField()),
                ('placas', models.CharField(max_length=7)),
                ('activo', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.colorvehiculo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.empleado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.marcavehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.tipovehiculo')),
            ],
        ),
    ]
