# Generated by Django 4.2.5 on 2023-10-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0003_remove_empleado_jefe_inmediato'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jefe_inmediato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.empleado'),
        ),
    ]
