# Generated by Django 4.2.5 on 2023-10-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0004_empleado_jefe_inmediato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placas',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateField()),
                ('tipo_acceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.tipoacceso')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.vehiculo')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
