# Generated by Django 4.2.5 on 2023-12-07 02:01

import acceso_vehicular.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0005_tipoacceso_alter_vehiculo_placas_logacceso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='Activo',
            new_name='activo',
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', acceso_vehicular.models.DayOfTheWeekField(choices=[('1', 'lunes'), ('2', 'martes'), ('3', 'miércoles'), ('4', 'jueves'), ('5', 'viernes'), ('6', 'sábado'), ('7', 'domingo')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso_vehicular.empleado')),
            ],
        ),
    ]
