# Generated by Django 4.2.5 on 2023-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0006_rename_activo_empleado_activo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
