# Generated by Django 4.2.5 on 2023-12-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0007_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
