# Generated by Django 4.2.5 on 2023-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_vehicular', '0009_logacceso_excepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacceso',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
